### ISSUE TITLE
Falta completar nombre, foto, y descripción

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-Carla-Benitez#1]
¡Hola @Carla-Benitez !
¿Qué pasó que no subiste tu nombre, foto y descripción? Acordate de preguntarnos cualquier problema.

¡Saludos!

**Comment by Carla-Benitez** [comment]
Hola profe!

disculpe que colgue con el trabajo pero me apareció un problema, yo tenia de antes instalado vscode y git (asociada a otra cuenta de GitHub) y ahora no me deja subir a esta cuenta de GitHub, me dice que no tengo permiso. 

![WhatsApp Image 2021-04-10 at 19 48 57](https://user-images.githubusercontent.com/82155594/114286721-aa8a4800-9a37-11eb-8004-2ab6aabafac0.jpeg)

**Comment by Carla-Benitez** [comment]
no se bien de como hacer para dale el acceso a la cuenta del github

**Comment by PalumboN** [comment]
Holaaa, me meto para darte una mano @Carla-Benitez 

Si usás Windows tenés que ir al [Administrador de Credenciales](https://support.microsoft.com/es-es/windows/obtener-acceso-al-administrador-de-credenciales-1b5c916a-6a16-889f-8581-fc16e8165ac0) y ver si está la cuenta vieja y borrarla. Después reiniciar el VSCode y, si no lo hiciste ya, te va a pedir un login con la nueva cuenta. Avisá si necesitás ayuda con eso.

Si usás Linux creo que eso no debería pasarte, avisá y lo vemos.

**Comment by Carla-Benitez** [comment]
Holaa, mil gracias!! Ya está, subí la foto y la descripción.🙌

**Comment by PalumboN** [comment]
Vamos!! :muscle:
